### ISSUE TITLE
Need a v1 release in order to use

### ISSUE THREAD

**Issue by ttomsu** [lee-dohm/last-assigned#1]
I think we need a release in order to use this GHA. Here's the error I'm getting:

```
Download action repository 'lee-dohm/last-assigned@v1'
##[warning]Failed to download action 'https://api.github.com/repos/lee-dohm/last-assigned/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
```

**Comment by lee-dohm** [comment]
Apologies that it took so long for me to get back to this, but it's [fixed now](https://github.com/lee-dohm/last-assigned/releases/tag/v1).
